### ISSUE TITLE
Problema no Envio de URL

### ISSUE THREAD

**Issue by cesguto** [enricodias/smsdev-php#4]
Ola.

Quando realizo envio de SMS contendo URL por algum motivo a api da smsdev faz um replace pelo texto "[LINK_CONTA_GRATIS]".
Poderiam avaliar esse bug?

**Comment by enricodias** [comment]
Isso não é um bug e não tem relação com o pacote smsdev-php. Isso é provavelmente uma limitação da própria smsdev para evitar publicidade usando a conta gratuita
